### ISSUE TITLE
Generated files are read-only (Windows)

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/JuDoc.jl#179] opened 2019-06-16 14:30 UTC
Don't know how to provide an MWE for this issue. I ran
```
Microsoft Windows [Version 10.0.18362.175]
(c) 2019 Microsoft Corporation. Minden jog fenntartva.

C:\Users\Ipse>cd C:\Users\Ipse\Documents\Code

C:\Users\Ipse\Documents\Code>julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using JuDoc

julia> newsite("test")
✓ Website folder generated at "test" (now the current directory).
→ Use serve() from JuDoc to see the website in your browser.

julia>                                                                                                                                                                  
```
and every file has read-only attribute. Dou you have any idea why this happens?
(I'm on `#master`, but the same happens with the latest version too.)

**Comment by tlienart** [comment] 2019-06-17 01:51
Ha, it's funny because I literally just realised that this is what causes #177 . Though if I'm not mistaken it's not all files that are read only but CSS files primarily? (or copied elements). I need to figure out how to copy the files on windows without this happening but that shouldn't be hard and hopefully will fix a bunch of things. Thanks for reporting!

**Comment by tlienart** [comment] 2019-06-17 04:39
closed this too quickly, effectively this is fixed in JuDocTemplates with a patch release to make sure that the `newsite` command generates a folder with 0o777 rights. 
I'll do a bit more testing, this should also fix minification problems on windows. 

Once the patch release is merged by JuliaRegistry, the problem should be fixed.

**Comment by tlienart** [comment] 2019-06-17 05:21
Ok the fix is merged, you'll just have to update JuDoc ( `add JuDoc#master` ), I've now tested this enough in #172 to be confident the problem is fixed.

**Closed by tlienart** 2019-06-17 05:21 UTC
Labels: windows

**Comment by cserteGT3** [comment] 2019-06-17 08:39
Just wanted to confirm, that it works fine!
