### ISSUE TITLE
[FR] Generalise the use of dot syntax to include assets

### ISSUE THREAD

**Issue by Invarianz** [tlienart/JuDoc.jl#170] opened 2019-06-05 13:36 UTC
First off, thanks for the nice evaluation feature. It works in principle and I can already use it productively. However, I encountered a problem where the code folder is created twice. I have the following tree:
```
├── src
│   ├── index.md
│   └── pages
│       ├── physics
│       │   ├── tests
│       │   │   ├── hubbard_model.md
│       │   │   └── interacting_dot.md
...
```
Now if I add the following code to `interacting_dot.md`, a bug occurs.
~~~
```julia:./code/ex1
a = 10
@show a
```
~~~
There are two seperate `code` folders created in `/assets/` i.e.:
```
├── assets
│   ├── pages
│   │   ├── code
│   │   │   ├── ex1.jl
│   │   │   └── output
│   │   │       └── ex1.out
│   │   ├── physics
│   │   │   ├── tests
│   │   │   │   └── code
│   │   │   │       ├── ex1.jl
│   │   │   │       └── output
│   │   │   │           └── ex1.out
...
```
Off topic: It would be great to have the dot syntax i.e. `./` also when including images or linking with markdown e.g. `[Important Paper](./papers/importantpaper.pdf)` in `interacting_dot.md` resolving to `/assets/pages/physics/tests/papers/importantpaper.pdf`. Right now I use your suggested `LaTeX` commands as workaround.

**Comment by tlienart** [comment] 2019-06-06 06:23
Thanks a lot for the report, I can reproduce and should be able to fix this very soon.

#### off topic point

yes I thought about this if what you're suggesting is that this:

```markdown
![](./ex1)
```

corresponds to 

```html
<img src="/assets/[correct subpath]/ex1.png">
```

I guess I was a bit reluctant of doing this because there's an ambiguity when users write this. In another generator, the syntax above would try to look "next to" the file so something like

```html
<img src="/pub/[correct subpath]/ex1.png">
```

which is also valid. 

Of course we could tell users to not use that kind of stuff and strongly encourage them to put all their assets in the `/assets/`, but I'd rather leave things flexible so that users can do more or less what they want (opinion is welcome here). 

#### alternative

What I'd suggest instead is to support more "native" latex-like commands + encourage users to define their own (like what you're doing). So for instance the current `\output` command works pretty much in the way you expect:

```markdown
\output{./code/ex1} 
```

(this includes the stdout output of the code, so for instance for the short snippet you showed above it would give `<pre><code>10</code></pre>`)

We could likewise have a  default`\fig` command that does a similar thing:

```markdown
\fig{./code/ex1}
```

which would convert to something like

```
<img src="/assets/[proper subpath]/code/ex1.png>
```

Possibly `\fig{}{./code/ex1}` to allow specification of another name than just `ex1` for the figure so that you could also use `\plot{plot1}{./code/ex1}` which would look for a `plot1.[ext]` in the relevant assets subfolder.

Thoughts?

**Comment by tlienart** [comment] 2019-06-06 07:42
Initial issue is fixed, it was due to a stupid mistake on my side not specifying the path to the page currently being processed at the right spot... anyway with your exact example, I now get for the assets folder:

```
.
├── infra
│   ├── favicon.png
│   ├── hamburger.svg
│   └── rndimg.jpg
├── pages
│   ├── code
│   │   ├── ex2.jl
│   │   ├── ex3.jl
│   │   └── output
│   │       ├── ex2.out
│   │       └── ex3.out
│   ├── exdot.jl
│   ├── output
│   │   └── exdot.out
│   └── physics
│       └── tests
│           └── code
│               ├── ex1.jl
│               └── output
│                   └── ex1.out
```

Please do give it a shot and let me know. 

Thanks a lot for reporting.

Ps: I'm editing the title as this issue is fixed but there's this secondary issue of paths for which your opinion is welcome.

**Comment by Invarianz** [comment] 2019-06-10 20:53
As you said, the inital issue seems to be fixed and everything is working as expected now!
The `\fig{}` command looks like a great idea however, I do not believe hat an additional command `\plot{}{}` is necessary. As far as I see it, the only benefit is that it somehow logically links the plot name to the output of a script called `ex.jl` in the markdown document. The `\fig{}` command should be more than enough to handle this by specifying the complete image name e.g. `\fig{./code/output/plot1.png}` or \fig{./code/output/plot1}`.
An additional command would be needed for linking arbitrary files into the document using the dot syntax. Something like `\link{.reviews/importantreview.pdf}`, where one always has to specify the file extension.

**Comment by tlienart** [comment] 2019-06-11 03:10
Sounds good, thanks for the feedback! I'll close this now, see issue #172 for the `\fig` and `\link`.

**Closed by tlienart** 2019-06-11 03:10 UTC
Labels: brainstorm, investigate, paths
